"use client";
import { useState, useTransition } from "react";
import { KeyRound, Plus, ShieldCheck, UserX } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/ui/page-header";
import { Surface } from "@/components/ui/surface";
import { useToast } from "@/components/ui/toast";
import { ModalPortal } from "@/components/ui/modal-portal";
import { createControllerAction, resetControllerPasswordAction, setControllerActiveAction } from "@/server/controllers/actions";

type Controller = { id: string; displayName: string; isActive: boolean; lastLoginAt: Date | null; createdAt: Date; _count: { checkInAttempts: number } };
export function ControllersPageClient({ initialControllers }: { initialControllers: Controller[] }) { const [controllers, setControllers] = useState(initialControllers); const [createOpen, setCreateOpen] = useState(false); const [passwordFor, setPasswordFor] = useState<Controller | null>(null); const { toast } = useToast(); const [pending, start] = useTransition(); const create = (form: FormData) => start(async () => { const result = await createControllerAction(form); if (result.error) return toast({ title: "Création impossible", description: result.error, variant: "error" }); toast({ title: "Contrôleur créé", description: "Transmettez-lui son e-mail et mot de passe de manière sécurisée.", variant: "success" }); setCreateOpen(false); window.location.reload(); }); const toggle = (controller: Controller) => start(async () => { const result = await setControllerActiveAction(controller.id, !controller.isActive); if (result.error) return toast({ title: "Mise à jour impossible", description: result.error, variant: "error" }); setControllers((items) => items.map((item) => item.id === controller.id ? { ...item, isActive: !item.isActive } : item)); toast({ title: controller.isActive ? "Contrôleur désactivé" : "Contrôleur activé", variant: "success" }); }); const reset = (form: FormData) => { if (!passwordFor) return; start(async () => { const result = await resetControllerPasswordAction(passwordFor.id, String(form.get("password") ?? "")); if (result.error) return toast({ title: "Réinitialisation impossible", description: result.error, variant: "error" }); toast({ title: "Mot de passe réinitialisé", description: "Transmettez le nouveau mot de passe manuellement.", variant: "success" }); setPasswordFor(null); }); };
return <div className="space-y-5"><PageHeader title="Contrôleurs" description="Comptes autorisés à scanner les billets à l’entrée." actions={<Button onClick={() => setCreateOpen(true)} icon={<Plus className="size-4" />}>Ajouter un contrôleur</Button>} /><Surface className="overflow-hidden shadow-sm"><div className="divide-y divide-border">{controllers.length ? controllers.map((controller) => <div key={controller.id} className="flex flex-col gap-3 px-4 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"><div><div className="flex items-center gap-2"><p className="font-semibold text-text">{controller.displayName}</p><span className={controller.isActive ? "text-sm text-success" : "text-sm text-text-muted"}>{controller.isActive ? "Actif" : "Désactivé"}</span></div><p className="mt-1 text-sm text-text-muted">{controller._count.checkInAttempts} contrôle{controller._count.checkInAttempts > 1 ? "s" : ""} · dernière connexion : {controller.lastLoginAt ? new Date(controller.lastLoginAt).toLocaleString("fr-FR") : "jamais"}</p></div><div className="flex gap-2"><Button size="sm" variant="secondary" onClick={() => setPasswordFor(controller)} icon={<KeyRound className="size-4" />}>Mot de passe</Button><Button size="sm" variant={controller.isActive ? "danger" : "secondary"} loading={pending} onClick={() => toggle(controller)} icon={<UserX className="size-4" />}>{controller.isActive ? "Désactiver" : "Activer"}</Button></div></div>) : <div className="p-8 text-center text-sm text-text-muted">Aucun contrôleur n’est encore configuré.</div>}</div></Surface>{createOpen ? <Dialog title="Ajouter un contrôleur" onClose={() => setCreateOpen(false)} onSubmit={create} pending={pending}><Field name="displayName" label="Nom affiché" /><Field name="email" label="E-mail" type="email" /><Field name="password" label="Mot de passe temporaire" type="password" /><p className="text-xs text-text-muted">Le mot de passe sera communiqué manuellement au contrôleur.</p><Button type="submit" loading={pending}>Créer le contrôleur</Button></Dialog> : null}{passwordFor ? <Dialog title={`Nouveau mot de passe — ${passwordFor.displayName}`} onClose={() => setPasswordFor(null)} onSubmit={reset} pending={pending}><Field name="password" label="Nouveau mot de passe" type="password" /><Button type="submit" loading={pending}>Enregistrer le mot de passe</Button></Dialog> : null}</div>; }
function Field({ name, label, type = "text" }: { name: string; label: string; type?: string }) { return <label className="block text-sm font-medium text-text">{label}<Input required name={name} type={type} minLength={type === "password" ? 8 : undefined} className="mt-1.5" /></label>; }
function Dialog({ title, children, onClose, onSubmit, pending }: { title: string; children: React.ReactNode; onClose: () => void; onSubmit: (form: FormData) => void; pending: boolean }) { return <ModalPortal><div className="fixed inset-0 z-[100] flex items-end justify-center sm:items-center"><button className="absolute inset-0 bg-text/35 backdrop-blur-[2px]" onClick={onClose} aria-label="Fermer" /><form action={onSubmit} className="relative w-full max-w-md space-y-4 rounded-t-md border border-border bg-surface p-5 shadow-overlay sm:rounded-md sm:p-6"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-primary" /><h2 className="text-lg font-semibold text-text">{title}</h2></div>{children}<Button type="button" variant="ghost" onClick={onClose} disabled={pending}>Annuler</Button></form></div></ModalPortal>; }
